initialize dgfip specific backend
MLanguage/mlang pull request #51
Opened 2021-08-09 11:56 UTC by jemsab

closes #19

2021-08-09 13:43 UTC, denismerigoux reviewed
I have the impression that is is a draft that duplicates the C backend, I'll switch it to draft until this actually contains the specific DGFiP backend.

2021-08-09 13:43 UTC, denismerigoux commented on examples/c_dgfip/README.md
> +is a `double` wrapped with a boolean flag to indicate if the value is undefined.
I don't think this doc is up to date with what you plan to do with the DGFiP backend, I would prefer you remove the text and put a placeholder until you write specific doc for it.

2021-08-09 15:13 UTC, jemsab commented
Now that I know how to get CI working, it would be probably be a good time to implement tests in the main makefile for the DGFiP backend.

2021-08-18 14:25 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/fuzz_harness.c
> +#include "ir_tests.h"
I think you can remove this file, this is not a priority for the new backend.

2021-08-18 14:25 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/fuzz_inputs/length_of_private_tests_2018
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pretium, risus eu porttitor tempor, orci nisi laoreet urna, vel mattis ex tellus eget urna. Donec eu vulputate risus, vitae convallis tur
Idem, can remove

2021-08-18 14:25 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/fuzz_inputs/length_of_private_tests_2019
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tempus euismod ligula, sit amet blandit elit imperdiet et. Vestibulum sit amet turpis hendrerit, accumsan odio at, aliquet odio. Integer
Idem, can remove

2021-08-18 14:25 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/fuzz_inputs/length_of_random_tests_2018
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet accumsan arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean rutrum
Idem, can remove

2021-08-18 14:26 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/fuzz_inputs/length_of_simulateur_simplifie_2018
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum lectus mauris, vel suscipit ex finibus non. In posuere molestie sem vitae faucibus. Nam sem est, vestibulum id tempus id, laci
Idem, can remove

2021-08-18 14:26 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/perf_harness.c
> +#include "ir_tests.h"
I think you can also remove that file

2021-08-18 14:26 UTC, denismerigoux commented on examples/dgfip_c/backend_tests/sanitize_crash_names.sh
> +#! /bin/bash
Remove, used for fuzzing

2021-08-18 14:27 UTC, denismerigoux commented on examples/dgfip_c/run_all_ins_selected_outs_2018.c
> +
I think you can remove? This is just a toy example program

2021-08-18 14:27 UTC, denismerigoux commented on examples/dgfip_c/run_complex_case_2018.c
> +#include "ir_complex_case_2018.h"
Idem, can remove

2021-08-18 14:27 UTC, denismerigoux commented on examples/dgfip_c/run_simulateur_simplifie_2018.c
> +#include "ir_simulateur_simplifie_2018.h"
Idem, can remove

2021-08-18 14:28 UTC, denismerigoux commented on examples/dgfip_c/Makefile
> +	MPP_FILE?=../../mpp_specs/2019_8_0.mpp
This should be changed to `dgfip_base.m` right ?

2021-08-18 14:29 UTC, denismerigoux commented on mpp_specs/dgfip_base.mpp
> +outputs <- call_m()
You're supposed to put that in a function (see other M++ files)

2021-08-18 14:29 UTC, denismerigoux commented on src/mlang/driver.ml
> +            Cli.debug_print "Compiling the codebase to DGFiP C...";
You should also modify the usage message related to the backend option in `cli.ml`.

2021-08-18 17:06 UTC, jemsab commented
@denismerigoux CI is failing because of the calculation tests. As you know in order to give the right results we have to use the functions in the M++ specs.  How do you want to proceed? Can this branched be merged as is with incorrect results?

2021-08-19 07:52 UTC, denismerigoux commented
Hum the problem is that if you want to test the DGFiP backend in real conditions you need the INTER files and the AUTOTEST. So what we really should do is setup the INTER files and autotest on Raphaël's machine, and set up the correct CI pipeline there. But for this PR we can leave this out, and simply remove `test_dgfip_backend` from the current CI pipeline.

2021-08-19 07:53 UTC, denismerigoux requested changes

2021-08-19 07:53 UTC, denismerigoux commented on .gitlab-ci.yml
> +test_dgfip_c_backend:
You can remove that for now

2021-08-19 09:04 UTC, denismerigoux approved these changes

2021-08-19 12:17 UTC, merged